import React from 'react';

import { Navigation, NavigationItem } from 'components/navigation';
import { Logo, LogoStar } from 'components/logo';
import { seoTitle } from 'helpers';
import { Head } from 'framework';
import { A } from 'elements';

import styles from './site.module.scss';

interface Props {
  children: React.ReactNode;
  navigationItems: NavigationItem[];
  title?: string;
}

export const Layout = ({ children, navigationItems, title = '' }: Props): JSX.Element => {
  return (
    <div className={styles.Layout}>
      <Head key="head">
        <title>{seoTitle(title)}</title>
      </Head>
      <header className={styles.Header}>
        <A href="/" className={styles.Header__link}>
          <Logo />
        </A>
        <Navigation items={navigationItems} />
      </header>
      <main>{children}</main>
      <footer className={styles.Footer}>
        <LogoStar className={styles.Footer__logo} />
        <p>
          <A href="https://nextjs.org/" rel="external">
            Generated by Next.js
          </A>
          <A href="https://vercel.com/" rel="external">
            Hosted at Vercel
          </A>
          <A href="https://github.com/wolfiezero/wolfiezero" rel="external me">
            Source on Github
          </A>
        </p>
        <p>Copyright 2020</p>
      </footer>
      <script
        src="//instant.page/5.0.1"
        type="module"
        integrity="sha384-0DvoZ9kNcB36fWcQApIMIGQoTzoBDYTQ85e8nmsfFOGz4RHAdUhADqJt4k3K2uLS"
      />
    </div>
  );
};
